<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.libraryexpress</groupId>
        <artifactId>LibraryExpress</artifactId>
        <version>0.1.7-SNAPSHOT</version>
    </parent>

    <artifactId>coverage-report</artifactId>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <name>LibraryExpress - Coverage Report</name>
    <description>
        Aggregator module responsible solely for consolidating JaCoCo coverage reports from the domain, application, and infrastructure layers into a single HTML report. It contains no production code.
    </description>

    <dependencies>
        <dependency>
            <groupId>org.libraryexpress</groupId>
            <artifactId>domain</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.libraryexpress</groupId>
            <artifactId>application</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.libraryexpress</groupId>
            <artifactId>infrastructure</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>

                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>verify</phase>

                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>

                        <configuration>
                            <dataFileIncludes>
                                <dataFileInclude>**/jacoco-unit.exec</dataFileInclude>
<!--                                <dataFileInclude>**/jacoco-integration.exec</dataFileInclude>-->
                                <dataFileInclude>**/jacoco-merged.exec</dataFileInclude>
                            </dataFileIncludes>

                            <excludes>
                                <exclude>**/dto/**/*</exclude>
                                <exclude>**/core/**/*</exclude>
                                <exclude>**/mapper/*</exclude>
                                <exclude>**/exception/*</exclude>
                                <exclude>**/cli/**/*</exclude>
                                <exclude>**/config/**/*</exclude>
                                <exclude>**/util/*</exclude>
                                <exclude>**/InMemory/*</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>